### ISSUE TITLE
Chinese font(s) are not correctly supported

### ISSUE THREAD

**Issue by 1900forever** [pingflood/GMenuNext#3]
Both Simplified and Traditional Chinese are not correctly supported.
￼
![1528179290475](https://user-images.githubusercontent.com/3516677/40958174-e32f7802-68ca-11e8-85a5-042f3ecb60a5.jpg)

**Comment by 1900forever** [comment]
I replaced the font.ttf file from the skins/default with Source Han Sans:
https://github.com/adobe-fonts/source-han-sans
Problem solved.

I wonder if all the skins can share the same font file so that Chinese/Japanese/Korean language can be correctly displayed?

**Comment by 1900forever** [comment]
Thanks a lot @pingflood

**Comment by pingflood** [comment]
New release is out with Unicode font supporting Chinese, Korean, Japanese and Russian.
